### ISSUE TITLE
TenSQR.py does not accept generically named config files

### ISSUE THREAD

**Issue by maciejmotyka** [SoYeonA/TenSQR#2]
I am used to having "samplename.sam", "samplename.fasta" and "samplename_config" files when working with aBayesQR and then specifying  the name of config file as an argument for the program. When trying the same approach with TenSQR:
```{bash}
for x in `ls *.sam | sed 's/.sam//'`
do
../ExtractMatrix $x\_config && python3 ../TenSQR.py $x\_config
done
```
the ExtrctMatrix script completes its job, but then TenSQR.py complains:
```
Traceback (most recent call last):
  File "../TenSQR.py", line 101, in <module>
    config_file = open('config', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'config'
```

I came up with this workaround, where as long as the file is named "config" I don't even have to put it into command as an argument:
```{bash}
for x in `ls *.sam | sed 's/.sam//'`
do
cat $x\_config >> config
python3 ../TenSQR.py
rm -f config
done
```
Thus I infer that TenSQR.py is looking for file named "config" instead of reading in the file specified by user.
Am I right? If yes, then please correct this. Small issue but inconvenient.

**Comment by WuLoli** [comment]
Hi LiptonTipton,

There are some parameters in the config file used as inputs to TenSQR.py.

Best,
Ziqi

**Comment by asynoeun** [comment]
Now TenSQR accepts config file named by user! Thanks for the suggestion!
